---
- name: elk docker config
  hosts: elk
  remote_user: azdmin
  become: true
  tasks:

  - name: Install Packages
    apt:
      update_cache: yes
#      force_apt_get: yes
      name: docker.io
      state: present

  - name: install python3-pip
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  #use pip mod
  - name: Install Docker Module
    pip:
      name: docker
      state: present

  - name: Use more memory
    sysctl:
      name: vm.max_map_count
      value: "262144"
      sysctl_set: yes
      state: present
      reload: yes

  - name: download and launch elk container
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044

  - name: enable service docker on boot
    systemd:
      name: docker
      enabled: yes
